name: flutter_scalify
description: The Ultimate Responsive Layout System. Features smart scaling, 6-tier grids, adaptive flex layouts, container queries, and 4K protection with zero-allocation math.
version: 2.2.3

homepage: https://github.com/alaa989/flutter_scalify
repository: https://github.com/alaa989/flutter_scalify
issue_tracker: https://github.com/alaa989/flutter_scalify/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - responsive
  - scaling
  - grid
  - layout
  - container-queries

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: