name: flutter_scalify
description: A powerful and elegant Flutter package for responsive design. Easily scale UI elements across all screen sizes with defensive null-safety.
version: 1.0.1

homepage: https://github.com/alaa989/flutter_scalify
repository: https://github.com/alaa989/flutter_scalify
issue_tracker: https://github.com/alaa989/flutter_scalify/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - responsive
  - ui
  - scaling
  - adaptive
  - layout

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: