name: flutter_scalify
description: The Intelligent Scaling Engine for Flutter. High-performance responsive design with 4K protection, container queries (local scaling), and zero-allocation architecture.
version: 2.0.1

homepage: https://github.com/alaa989/flutter_scalify
repository: https://github.com/alaa989/flutter_scalify
issue_tracker: https://github.com/alaa989/flutter_scalify/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - responsive
  - scaling
  - performance
  - container-queries
  - desktop

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: